### ISSUE TITLE
目次

### ISSUE THREAD

**Issue by kawasin73** [kawasin73/knowledge-public#1]
## 勉強になるモジュール

- [ ] FoundationKit #2
- [ ] Apache Portable Runtime Module #3
- [ ] DPDK #10

## 読んだ本

- [x] プログラミング作法 #4
- [x] 省メモリプログラミング #5
- [ ] 詳解 UNIX プログラミング #32
- [x] Effective Java 第3版 #33
- [x] Android を支える技術 I  #34 
- [x] Android を支える技術 Ⅱ #35
- [ ] #36 

## 調査

- [ ] システムコール（Linux） #11 
- [ ] mmap #15
- [ ] SILO：DB の新しいトレンド
- [ ] hash map テーブルの拡張サイズ（素数？）
- [x] メモを管理するアプリ #24 
- [ ] DJB #22 
- [ ] framegraph パフォーマンスを見るツール

## １人前のプログラマになるために

- [ ] httpサーバーをフルスクラッチで C 言語で実装する #20 
- [ ] C 言語に詳しくなる #21 
- [ ] nginx のプラグインを作ってみる #26
- 競技プログラミング #27

## 参考になるサイト

- [asciiflow](http://asciiflow.com/)
  - 文字列で簡単な絵をかけるサイト
- [stackedit](https://stackedit.io)
  - マークダウンエディタ
  - mermaid でフロー図を書くことができる
- [Rosetta Code](http://www.rosettacode.org/wiki/Rosetta_Code)
  - 様々なタスクを複数の言語でそれぞれどのように実装するかをまとめている
- [HackerRank](https://www.hackerrank.com)
  > ソフトウェアエンジニアのスキルをスコア化し、企業の適切な技術者採用につなげるプラットフォーム
  > コード・チャレンジ」と呼ばれる35のプログラミング言語、4000を超える無料公開のテストによって自らのスキルを証明することができ、また企業が設定した特定の問題を解くことで、成果によっては面接に進み採用オファーをもらうことができる
  > https://svs100.com/hackerrank-2/
- [overleaf](https://ja.overleaf.com/)
  - LaTex のブラウザエディタ
- [draw.io](draw.io)

## 学んだこと

- 技術ドキュメンテーションの考え方 #19
- ソフトウェアの解説ドキュメントの着目点 #18
- 技術選定のドキュメントのまとめ方 #6 
- 設計のやり方 #9
- issue の考え方  #23 
- ベンチマークの取り方 #12 
- コーディングをするときの心得 #31 

## アルゴリズムなど

- [x] postgres における xid の wraparound #7
- [x] B-tree のアルゴリズムと実装 #8 
- [x] メモリアロケーションにおけるフラグメンテーションへの対策 #14
- [x] 基数木（Patricia tree, Radix tree）#25
- [ ] KVS におけるコンパクション #29
- [ ] ファイルシステムのジャーナリング #30 
- [ ] Lock-free と Wait-free

## パフォーマンス比較

- [x] Golang におけるインターフェイス呼び出しと関数ポインタ呼び出しの比較 https://github.com/kawasin73/bibit/issues/2
- [x] Mmap へのデータ書き込みをバッファリングするかどうか #13

## その他

- [ ] 鉄拳のオンラインゲームの設計
